### PR TITLE
Add warning suppression for changed stores, and a test for it

### PR DESCRIPTION
**Pull request by dropfen**
fixes: #182

### CODE REVIEW

**Comment by jzaefferer** [comment]
Probably also needs docs updates, maybe mention the new prop somewhere under https://github.com/mobxjs/mobx-react#provider-and-inject ?

**Comment by dropfen** [comment]
Note added.

**Comment by dropfen** [comment]
@jzaefferer You are right, I added it extra because it makes it clear, that this is a boolean. should't be a blocker.

**Comment by mweststrate** [comment]
Looking good, thanks!

**Pull request merged**
