### PR TITLE
Convert build to use rollupjs as the bundler instead of webpack

### PR DESCRIPTION
**Pull request by rossipedia**
This PR updates mobx-react to use [rollup](https://rollupjs.org) as the bundler instead of webpack. For motivation, see [this blog post](https://nolanlawson.com/2016/08/15/the-cost-of-small-modules/). Also, bundling as a flat UMD means that any webpack project that includes mobx-react won't end up with multiple copies of the Webpack runtime embedded in their app.

This has resulted in a significant size decrease as well:

**Current Webpack build sizes** (I've omitted the module lists for brevity)

```
Hash: 369040fad2c86258698356e89ad2e3ef83ea6ad64a39813d95fc6954b3b2b9a6008b2137eff363a3
Version: webpack 2.4.1
Child
    Hash: 369040fad2c862586983
    Time: 2129ms
       Asset     Size  Chunks             Chunk Names
    index.js  41.8 kB       0  [emitted]  main

Child
    Hash: 56e89ad2e3ef83ea6ad6
    Time: 2117ms
        Asset     Size  Chunks             Chunk Names
    native.js  41.8 kB       0  [emitted]  main

Child
    Hash: 4a39813d95fc6954b3b2
    Time: 2116ms
        Asset     Size  Chunks             Chunk Names
    custom.js  41.5 kB       0  [emitted]  main

Child
    Hash: b9a6008b2137eff363a3
    Time: 2116ms
           Asset     Size  Chunks             Chunk Names
    index.min.js  17.8 kB       0  [emitted]  main
```

**New Rollup build sizes**

```
> node build-rollup.js && cp src/index.d.ts index.d.ts && cp src/index.d.ts native.d.ts && cp src/index.d.ts custom.d.ts

┌────────────────────────────────────────────────────────┐
│                                                        │
│   Destination: ~/code/mobx-react/index.js              │
│   Bundle size: 28.39 KB, Gzipped size: 8.07 KB         │
│                                                        │
└────────────────────────────────────────────────────────┘
┌─────────────────────────────────────────────────────────┐
│                                                         │
│   Destination: ~/code/mobx-react/native.js              │
│   Bundle size: 28.31 KB, Gzipped size: 8.06 KB          │
│                                                         │
└─────────────────────────────────────────────────────────┘
┌────────────────────────────────────────────────────────────┐
│                                                            │
│   Destination: ~/code/mobx-react/index.min.js              │
│   Bundle size: 11.69 KB, Gzipped size: 4.35 KB             │
│                                                            │
└────────────────────────────────────────────────────────────┘
┌─────────────────────────────────────────────────────────┐
│                                                         │
│   Destination: ~/code/mobx-react/custom.js              │
│   Bundle size: 28.19 KB, Gzipped size: 8.03 KB          │
│                                                         │
└─────────────────────────────────────────────────────────┘
```

That's at least a 30% size decrease across the board.

I've run the test suite and both bundlers produce the same output (I believe
there's currently one failing test).

I've also rebased this branch on to my [other pull request](https://github.com/mobxjs/mobx-react/pull/243) as I wanted to be able to run the tests to verify nothing broke.

### CODE REVIEW

**Comment by rossipedia** [comment]
This needs work. `@observer`s aren't being re-rendered at the moment (not sure why when tests are passing).

**Comment by rossipedia** [comment]
I'm re-opening this. The bug I experienced was due to the fact that I had run `npm link mobx-react` in my test project. Due to the way that I had webpack set up for that project, multiple copies of mobx were being included: `mobx-react` resolved `require("mobx")` to the version in _its_ `node_modules` folder, and my app also had a `require("mobx")`. Upon resolving that issue with webpack's `resolve.modules` feature so that only a single version of `mobx` was included, things started working fine.

**Comment by rossipedia** [comment]
Are there any blockers on this? I'd be more than happy to help out if needed

**Comment by mweststrate** [comment]
No none at all, this makes complete sense! Actually opened an issue yesterday on Mobx package itself to do the same there. I just hadn't time to review / test it yet :-(. If somebody else feels for doing that, welcome as well! 

cc: @andykog  / @mattiamanzati ?

**Comment by andykog** [comment]
Played around with it a bit, looks and works absolutely fine (checked using with/without modules, react-native) 👍

**Comment by mweststrate** [comment]
Thanks for reviewing @andykog!

Will cut a new release tomorrow :)

**Comment by rossipedia** [comment]
🎉 🎈 🎉

**Comment by mweststrate** [comment]
Seems to be an issue with the UMD built. Or is it consumed wrongly? https://jsfiddle.net/mweststrate/wv3yopo0/1238/

**Comment by andykog** [comment]
Unpublished `mobx-react@4.2.0-rollup`
Investigating

**Comment by rossipedia** [comment]
Looks like this is an error with these lines:

``` js
export default module.exports;

/* DevTool support */
if (typeof __MOBX_DEVTOOLS_GLOBAL_HOOK__ === 'object') {
  __MOBX_DEVTOOLS_GLOBAL_HOOK__.injectMobxReact(module.exports, mobx)
}
```

As ES modules don't define `module`. The fix should be to use the ambient `exports` variable by itself, as this is passed into the UMD wrapper function. I've submitted #265 for a fix

**Comment by myknbani** [comment]
Curious timing, webpack v3 now has scope hoisting, reducing bundle sizes as well.

**Comment by rossipedia** [comment]
While true, in my testing mobx/mobx-react didn't benefit as much with Webpack's module concatenation as they do with rollup

**Pull request merged**
