### PR TITLE
WIP: V4

### LINKED ISSUE #162: RN: unable to resolve react-dom on 4.0.0-rc3

### PR DESCRIPTION
**Pull request by mweststrate**
Open items

* [x] should state be made observable as well? See: https://github.com/mobxjs/mobx-react/pull/136#issuecomment-258881576. Cc @Strate 
* [x] merge #134  after adding tests
* [x] Evaluate https://github.com/mobxjs/mobx-react/tree/improve-proptypes-on-inject branch
* [x] Implement #111 (inject should be reactive)?
* [x] Implement #147 (provide UMD build), then update #118 
* [x] Implement #138, `Observer` regions
* [x] Merge in #160, always pure `observer`
* [x] Fix #162
* [x] always use `React.batchedUpdates`, even outside react events
* [x] release beta, verify v4 against some projects
* [x] run perf tests
* [ ] update deps of dev-tools
* [ ] Update docs (gh-pages branch of MobX)

### CODE REVIEW

**Comment by Strate** [comment]
@mweststrate as discussed at #136, I've added test case for `setState() -> reRender` case.

**Comment by mweststrate** [comment]
@Strate tnx!

`mobx-react@4.0.0-beta.1` is now available on NPM

**Comment by mweststrate** [comment]
Encountered reaction loops when testing rc.1 against our test suite. Will investigate further

**Comment by Strate** [comment]
@mweststrate great work! Could you please publish 4.0.0-rc.2 (or I can do it)

**Comment by mweststrate** [comment]
@Strate just did that a few  minutes ago :-D. It also includes #160 btw `mobx-react@4.0.0-rc.2`

**Comment by Strate** [comment]
@mweststrate what exactly included from #160? I don't see any commit...

**Comment by mweststrate** [comment]
Dôh, forgot to tag the commit: https://github.com/mobxjs/mobx-react/compare/v4...160-pure-observer?expand=1

**Pull request merged**
