### PR TITLE
Issue #155 - ES6 Test support

### PR DESCRIPTION
**Pull request by A-gambit**
Solve issue [#155](https://github.com/mobxjs/mobx-react/issues/155):

Add support of `es6` and `react` to tests and refactor them. 
Also add ability to build tests bundle and run it in browser: `npm run test:build`

@mweststrate please review

The next step to rewrite `jquery` to `enzyme` from some tests file.

### CODE REVIEW

**Comment by A-gambit** [comment]
@mweststrate there is no js linter in this repository. Is it ok? I can add `eslint`, in my next pull.

**Comment by andykog** [comment]
Vote for [eslint-config-airbnb](https://www.npmjs.com/package/eslint-config-airbnb)!

**Comment by A-gambit** [comment]
@andykog Yep! I think about it.
Also, I think it will be better to add `eslint` to MobX and MobX-Utils, too.

**Comment by mweststrate** [comment]
Looking great so far @A-gambit! and +1 for linting :)

**Comment by A-gambit** [comment]
@mweststrate Can I merge it in `v4`?

**Comment by A-gambit** [comment]
@andykog @mweststrate What do you think about semicoma rule? Do we need it? In my opinion, it is important in typescript files, but what about javascript? I have already start lint feature in mobx-utils.

**Comment by andykog** [comment]
I, personally, hate missing semicolons in JS :-)

**Comment by mweststrate** [comment]
@A-gambit yes feel free to merge.
Personally, I prefer no semicolons (even in typescript) but I can live with both. same for tabs or spaces. But I have a strong preference for width = 4 ;-)

**Comment by A-gambit** [comment]
@mweststrate @andykog I will create a pull in mobx-util soon and we will discuss code style there)

**Pull request merged**
