### PR TITLE
TypeScript, MobX-React, and RefObjects

### PR DESCRIPTION
**Pull request by 42shadow42**
Fixed issue where inject decorated classes were not compatible with strongly typed RefObjects

### CODE REVIEW

**Comment by 42shadow42** [comment]
Fixes #616 

This is missing unit tests currently and should be added, I'm not really an expert here so I wouldn't know how to write them myself.

This should be treated as a breaking change, as it affects the usage of wrappedInstance on RefObjects, the migration path is to remove the .wrappedInstance and use the item directly.

**Comment by mweststrate** [comment]
@42shadow42 I need a little clarification. Is the goal to fix typings, or do you want to enable refForwarding on `inject`? Which of those two would be according to you the correct fix?

In either case, could you demonstrate what you are fixing in a small reproduction (codesandbox, unit test or otherwise), so that the solution can be verified?

**Comment by 42shadow42** [comment]
@mweststrate The goal is to fix typings, the proposed solution is refForwarding.

Here is my reproduction:
[mobx-injector.zip](https://github.com/mobxjs/mobx-react/files/2672680/mobx-injector.zip)

If you look at parent-component.tsx you will see that typescript enforces typings of child and child2 variables, but the actual runtime types are inject wrappedInstances so while the typescript compiles runtime fails, the proposed fix of refForwarding makes the compile time type match the runtime type.

**Comment by mweststrate** [comment]
Thanks for the PR! I took the important changes, but refactored and cleaned up the as it got a bit messy in #644. Also added / updated tests. 

So closing this one in favor of that one, but thanks for pointing out the solution and will put your name on the contributors list!

**Pull request closed without merging**
