### PR TITLE
Allow signature of injecting component to differ from signature of injected component

### PR DESCRIPTION
**Pull request by timmolendijk**
Address #174

### CODE REVIEW

**Comment by timmolendijk** [comment]
Hmm, failing tests. Am I missing anything?

**Comment by tkrotoff** [comment]
You should write a test case here: https://github.com/mobxjs/mobx-react/blob/master/test/ts/compile-ts.tsx and verify everything works with `npm run test`. This way you ensure there will be no regression in the future.

**Comment by timmolendijk** [comment]
FYI: I am no longer using this package, so I won't find time to look into this any time soon.

**Comment by mweststrate** [comment]
Thanks for the update, closing for now.

**Pull request closed without merging**
