### PR TITLE
Observer warning test

### PR DESCRIPTION
**Pull request by delaetthomas**

### CODE REVIEW

**Comment by mweststrate** [comment]
Somehow CI fails on this without clear error. Locally tests run without issue..

**Comment by delaetthomas** [comment]
I don't get it. CI doesn't fail on one of my commits. Only on the merge commit. The syntax change is not the problem. That part I copied from an other test.

**Comment by andykog** [comment]
That's not @delaetthomas fault, I've restarted build from #136 and it fails too now. https://travis-ci.org/mobxjs/mobx-react/builds/169473113

**Comment by delaetthomas** [comment]
@andykog I made a special travis script. Now it doesn't fail anymore.

**Pull request merged**
