### PR TITLE
Optional dependencies to support Yarn PNP

### PR DESCRIPTION
**Pull request by FredyC**
Theoretical fix for #596

### CODE REVIEW

**Comment by mweststrate** [comment]
See also #479. Probably we could release this under a npm tag and ask few people to try

**Comment by ematipico** [comment]
Any news on this? I'm stuck with this

**Comment by FredyC** [comment]
Well, if we eventually utilize the https://github.com/mobxjs/mobx-react-lite/pull/214 in this package as well, it wouldn't be necessary to have this PR afaik.

**Comment by ematipico** [comment]
This PR is a minor/patch change, the other could be a breaking change. This could be merged straight away while the other is still open.

**Comment by FredyC** [comment]
Well, since there is not much of the interest in Yarn PNP, I will close this in favor #787 which I assume will be published soon and it's not a breaking change.

**Pull request closed without merging**
