### PR TITLE
Use circleci instead of travis for ci and add size-limit

### PR DESCRIPTION
**Pull request by pustovalov**
Size Limit is a linter for your JS application or library performance. It calculates the real cost of your JS for end users and throws an error if the cost exceeds the limit.

https://github.com/ai/size-limit

Example:
```
yarn run v1.15.2
$ size-limit

  Size limit:   10 KB
  Package size: 7.19 KB minified and gzipped
  Loading time: 144 ms  on slow 3G

Done in 0.80s.
```

Example of circle ci build: https://circleci.com/workflow-run/e32e556e-12f7-47af-865b-8043cf544224

### CODE REVIEW

**Comment by mweststrate** [comment]
@pustovalov would you remind rebasing this PR?

**Comment by pustovalov** [comment]
@mweststrate I have fixed the conflicts

CI build: https://circleci.com/workflow-run/f3742ca7-a2e9-48aa-bd01-53ee1a31e8b0

**Comment by FredyC** [comment]
@pustovalov I am not familiar with CircleCI. That link needs a login apparently. Does it have the option to see output publically? It's not viable asking every contributor to sign in with the service to see why are tests failing.

**Comment by FredyC** [comment]
I do wonder though, why CircleCI? Using size-limit is fine, but why to switch to CC? Does it bring any advantage? Plenty of OSS contributors are used to Travis UI. Using something else makes it only harder.

**Comment by pustovalov** [comment]
@FredyC sry, previous link was private. You can see a result of tests here: https://circleci.com/gh/pustovalov/mobx-react

I think CircleCI more flexible than Travis, and https://github.com/mobxjs/mobx-state-tree also uses CircleCI

**Comment by FredyC** [comment]
@xaviergonz Can you please review this since you originally configured CC for mobx-state-tree?

**Comment by pustovalov** [comment]
@FredyC @xaviergonz need to turn on `mobx-react` repo on circle and add `COVERALLS_REPO_TOKEN` to environment variables

**Comment by FredyC** [comment]
@xaviergonz I don't seem to have access to that, can you do it, please?

**Comment by xaviergonz** [comment]
Sure, I'll do it in some hours once I get home

**Comment by xaviergonz** [comment]
done: https://circleci.com/gh/mobxjs/mobx-react

**Comment by xaviergonz** [comment]
also: https://coveralls.io/github/mobxjs/mobx-react

**Pull request merged**
